services:
  api:
    build: .
    container_name: url-shortener
    ports:
      - "8000:8000"
    environment:
      - BASE_URL=http://localhost:8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped